#!/usr/bin/env python3

import random

def cpu_temperature(min_value=35, max_value=80.0):
    return random.uniform(min_value, max_value)

if __name__ == "__main__":
    cpu_temp = cpu_temperature()
    print(f"{cpu_temp:.2f}",end='')
