#!/usr/bin/env python3

import random

def temperature(min_value=15.0, max_value=35.0):
    return random.uniform(min_value, max_value)

if __name__ == "__main__":
    temp = temperature()
    print(f"{temp:.2f}", end='')
